[package]
name = "complete-example"
version = "0.1.0"
edition = "2021"
author = "alessandro98.mazza@gmail.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive", "cargo"] }
